
install.packages("ggplot2")
install.packages("tidyverse")
install.packages("dplyl")
install.packages("rinat")
install.packages("sf")
install.packages("rosm")
install.packages("ggspatial")
install.packages("leaflet")
install.packages("htmltools")
install.packages("mapview")
install.packages("leafpop")